# Experiment-2

In [1]:
import numpy as np

In [2]:
def activation_func(net):
    return 1 / (1 + np.exp(-net))

In [3]:
def calc_error(output, det_output):
    return (1/2)*(det_output - output)**2

#### Backpropogation

In [4]:
def forward_pass(x_input, weights, biases):
    net_h0 = (x_input[0] * weights[0]) + (x_input[1] * weights[1]) + biases[0]

    outh0 = activation_func(net_h0)


    net_h1 = (x_input[0] * weights[2]) + (x_input[1] * weights[3]) + biases[1]

    outh1 = activation_func(net_h1)


    net_o0 = (outh0 * weights[4]) + (outh1 * weights[5]) + biases[2]

    out_o0 = activation_func(net_o0)

    return outh0, outh1, out_o0

In [5]:
def backward_pass(x_input, weights, biases, desired_output, learning_rate, outh0, outh1, out_o0):
    delta_o0 = (desired_output - out_o0) * out_o0 * (1 - out_o0)

    delta_h0 = delta_o0 * weights[4] * outh0 * (1 - outh0)

    delta_h1 = delta_o0 * weights[5] * outh1 * (1 - outh1)

    dw0 = learning_rate * delta_h0 * x_input[0]
    dw1 = learning_rate * delta_h0 * x_input[1]
    dw2 = learning_rate * delta_h1 * x_input[0]
    dw3 = learning_rate * delta_h1 * x_input[1]
    dw4 = learning_rate * delta_o0 * outh0
    dw5 = learning_rate * delta_o0 * outh1
    dw_values = [dw0, dw1, dw2, dw3, dw4, dw5]

    db0 = learning_rate * delta_h0
    db1 = learning_rate * delta_h1
    db2 = learning_rate * delta_o0
    db_values = [db0, db1, db2]

    return dw_values, db_values

In [6]:
X = [1,0]
w = [0.5, -0.3, 0.8, 0.2, 0.6, -0.5]
b = [0.2, -0.4, 0.3]
d = [1]
learning_rate = 0.01

In [7]:
epochs = 10000
error_threshold = 0.001

X = [[1, 0]]
d = [1]

w = [0.5, -0.3, 0.8, 0.2, 0.6, -0.5]
b = [0.2, -0.4, 0.3]
learning_rate_initial = 0.5

def train(weights, biases, learning_rate, epochs, error_threshold):
    current_w = list(weights)
    current_b = list(biases)

    for epoch in range(epochs):
        total_epoch_error = 0

        for i in range(len(X)):
            x_input = X[i]
            desired_output = d[i]

            outh0, outh1, out_o0 = forward_pass(x_input, current_w, current_b)

            error = calc_error(out_o0, desired_output)
            total_epoch_error += error

            dw_values, db_values = backward_pass(x_input, current_w, current_b, desired_output, learning_rate, outh0, outh1, out_o0)

            for j in range(len(current_w)):
                current_w[j] += dw_values[j]

            for j in range(len(current_b)):
                current_b[j] += db_values[j]

        if epoch % 1000 == 0 or total_epoch_error < error_threshold:
            print(f"Epoch {epoch}: Total Error = {total_epoch_error:.6f}")
            print(f"  Output for input {X[0]}: {forward_pass(X[0], current_w, current_b)[2]:.4f}")

        if total_epoch_error < error_threshold:
            print(f"Stopping condition met at epoch {epoch+1}. Total Error ({total_epoch_error:.6f}) <= Threshold ({error_threshold:.6f})")
            break

    return current_w, current_b

updated_w, updated_b = train(w, b, learning_rate_initial, epochs, error_threshold)

print(f"\nFinal updated weights:")
for w in updated_w:
    print(f"\t{w:.4f}")
print(f"Final updated biases:")
for b in updated_b:
    print(f"\t{b:.4f}")

Epoch 0: Total Error = 0.080375
  Output for input [1, 0]: 0.6205
Epoch 289: Total Error = 0.000998
  Output for input [1, 0]: 0.9554
Stopping condition met at epoch 290. Total Error (0.000998) <= Threshold (0.001000)

Final updated weights:
	0.7865
	-0.3000
	0.7645
	0.2000
	1.5805
	0.2893
Final updated biases:
	0.4865
	-0.4355
	1.6615

#### On XOR input with SGD

In [8]:
# XOR input
x1 = [0, 0]
x2 = [0, 1]
x3 = [1, 0]
x4 = [1, 1]
y = [0, 1, 1, 0]

epochs = 2000
error_threshold = 0.001

X = [x1, x2, x3, x4]
d = y

w = [0.5, -0.3, 0.8, 0.2, 0.6, -0.5]
b = [0.2, -0.4, 0.3]
learning_rate_initial = 0.01

In [9]:
def train_SGD(X_data, y_data, epochs_count, lr_val, initial_weights_list, initial_biases_list):
    w1, w2, w3, w4, w5, w6 = (
        initial_weights_list[0],
        initial_weights_list[1],
        initial_weights_list[2],
        initial_weights_list[3],
        initial_weights_list[4],
        initial_weights_list[5],
    )
    b1, b2, b3 = initial_biases_list[0], initial_biases_list[1], initial_biases_list[2]

    for epoch in range(epochs_count):
        total_loss = 0
        for i in range(len(X_data)):
            x_input = X_data[i]
            target = y_data[i]

            current_weights = [w1, w2, w3, w4, w5, w6]
            current_biases = [b1, b2, b3]

            outh0, outh1, out_o0 = forward_pass(x_input, current_weights, current_biases)

            current_loss = calc_error(out_o0, target)
            total_loss += current_loss

            dw_values, db_values = backward_pass(
                x_input,
                current_weights,
                current_biases,
                target,
                lr_val,
                outh0,
                outh1,
                out_o0,
            )

            w1 += dw_values[0]
            w2 += dw_values[1]
            w3 += dw_values[2]
            w4 += dw_values[3]
            w5 += dw_values[4]
            w6 += dw_values[5]

            b1 += db_values[0]
            b2 += db_values[1]
            b3 += db_values[2]

        avg_loss = total_loss / len(X_data)

        print(f"Epoch {epoch+1}: Avg. Loss = {avg_loss}")

        # if epoch % 1000 == 0:
        #     print(f"Epoch {epoch}: Total Error = {total_loss:.6f}")
        #     for input_idx in range(len(X_data)):
        #         current_input = X_data[input_idx]
        #         output_for_input = forward_pass(
        #             current_input, [w1, w2, w3, w4, w5, w6], [b1, b2, b3]
        #         )[2]
        #         print(
        #             f"  Output for input {current_input}: {output_for_input:.4f} (Desired: {y_data[input_idx]}) "
        #         )

        if avg_loss < error_threshold:
            print(
                f"Stopping condition met at epoch {epoch+1}. Total Error ({total_loss:.6f}) <= Threshold ({error_threshold:.6f})"
            )
            break

    print("\nFinal updated weights:")
    print(f"\t{w1:.4f}")
    print(f"\t{w2:.4f}")
    print(f"\t{w3:.4f}")
    print(f"\t{w4:.4f}")
    print(f"\t{w5:.4f}")
    print(f"\t{w6:.4f}")
    print("Final updated biases:")
    print(f"\t{b1:.4f}")
    print(f"\t{b2:.4f}")
    print(f"\t{b3:.4f}")

    return [w1, w2, w3, w4, w5, w6], [b1, b2, b3]


print("Training for XOR dataset:")
updated_w_xor, updated_b_xor = train_SGD(
    X,
    d,
    epochs,
    learning_rate_initial,
    w,
    b,
)

Training for XOR dataset:
Epoch 1: Avg. Loss = 0.12970573935414975
Epoch 2: Avg. Loss = 0.12967188906830746
Epoch 3: Avg. Loss = 0.12963828210617
Epoch 4: Avg. Loss = 0.1296049169922561
Epoch 5: Avg. Loss = 0.12957179225586668
Epoch 6: Avg. Loss = 0.1295389064311367
Epoch 7: Avg. Loss = 0.1295062580570855
Epoch 8: Avg. Loss = 0.12947384567766607
Epoch 9: Avg. Loss = 0.12944166784181296
Epoch 10: Avg. Loss = 0.12940972310348897
Epoch 11: Avg. Loss = 0.12937801002173022
Epoch 12: Avg. Loss = 0.12934652716069076
Epoch 13: Avg. Loss = 0.12931527308968518
Epoch 14: Avg. Loss = 0.1292842463832305
Epoch 15: Avg. Loss = 0.12925344562108657
Epoch 16: Avg. Loss = 0.12922286938829536
Epoch 17: Avg. Loss = 0.12919251627521944
Epoch 18: Avg. Loss = 0.12916238487757878
Epoch 19: Avg. Loss = 0.12913247379648646
Epoch 20: Avg. Loss = 0.12910278163848374
Epoch 21: Avg. Loss = 0.12907330701557365
Epoch 22: Avg. Loss = 0.12904404854525336
Epoch 23: Avg. Loss = 0.1290150048505458
Epoch 24: Avg. Loss = 0.1289861745600298
Epoch 25: Avg. Loss = 0.12895755630786981
Epoch 26: Avg. Loss = 0.1289291487338438
Epoch 27: Avg. Loss = 0.12890095048337075
Epoch 28: Avg. Loss = 0.1288729602075367
Epoch 29: Avg. Loss = 0.12884517656312003
Epoch 30: Avg. Loss = 0.12881759821261574
Epoch 31: Avg. Loss = 0.12879022382425875
Epoch 32: Avg. Loss = 0.12876305207204594
Epoch 33: Avg. Loss = 0.12873608163575773
Epoch 34: Avg. Loss = 0.12870931120097834
Epoch 35: Avg. Loss = 0.12868273945911524
Epoch 36: Avg. Loss = 0.12865636510741776
Epoch 37: Avg. Loss = 0.12863018684899483
Epoch 38: Avg. Loss = 0.1286042033928314
Epoch 39: Avg. Loss = 0.12857841345380472
Epoch 40: Avg. Loss = 0.12855281575269906
Epoch 41: Avg. Loss = 0.1285274090162201
Epoch 42: Avg. Loss = 0.12850219197700813
Epoch 43: Avg. Loss = 0.12847716337365056
Epoch 44: Avg. Loss = 0.12845232195069362
Epoch 45: Avg. Loss = 0.12842766645865333
Epoch 46: Avg. Loss = 0.1284031956540255
Epoch 47: Avg. Loss = 0.12837890829929513
Epoch 48: Avg. Loss = 0.1283548031629449
Epoch 49: Avg. Loss = 0.128330879019463
Epoch 50: Avg. Loss = 0.12830713464935026
Epoch 51: Avg. Loss = 0.1282835688391264
Epoch 52: Avg. Loss = 0.12826018038133577
Epoch 53: Avg. Loss = 0.12823696807455212
Epoch 54: Avg. Loss = 0.12821393072338286
Epoch 55: Avg. Loss = 0.1281910671384727
Epoch 56: Avg. Loss = 0.12816837613650642
Epoch 57: Avg. Loss = 0.12814585654021107
Epoch 58: Avg. Loss = 0.1281235071783576
Epoch 59: Avg. Loss = 0.1281013268857617
Epoch 60: Avg. Loss = 0.1280793145032842
Epoch 61: Avg. Loss = 0.12805746887783062
Epoch 62: Avg. Loss = 0.12803578886235023
Epoch 63: Avg. Loss = 0.12801427331583476
Epoch 64: Avg. Loss = 0.12799292110331592
Epoch 65: Avg. Loss = 0.12797173109586313
Epoch 66: Avg. Loss = 0.1279507021705798
Epoch 67: Avg. Loss = 0.12792983321060003
Epoch 68: Avg. Loss = 0.127909123105084
Epoch 69: Avg. Loss = 0.12788857074921295
Epoch 70: Avg. Loss = 0.12786817504418407
Epoch 71: Avg. Loss = 0.1278479348972045
Epoch 72: Avg. Loss = 0.12782784922148482
Epoch 73: Avg. Loss = 0.12780791693623217
Epoch 74: Avg. Loss = 0.12778813696664298
Epoch 75: Avg. Loss = 0.12776850824389496
Epoch 76: Avg. Loss = 0.12774902970513888
Epoch 77: Avg. Loss = 0.1277297002934895
Epoch 78: Avg. Loss = 0.12771051895801683
Epoch 79: Avg. Loss = 0.12769148465373598
Epoch 80: Avg. Loss = 0.12767259634159733
Epoch 81: Avg. Loss = 0.1276538529884758
Epoch 82: Avg. Loss = 0.1276352535671603
Epoch 83: Avg. Loss = 0.1276167970563418
Epoch 84: Avg. Loss = 0.12759848244060212
Epoch 85: Avg. Loss = 0.1275803087104016
Epoch 86: Avg. Loss = 0.12756227486206662
Epoch 87: Avg. Loss = 0.12754437989777664
Epoch 88: Avg. Loss = 0.1275266228255512
Epoch 89: Avg. Loss = 0.12750900265923612
Epoch 90: Avg. Loss = 0.12749151841848974
Epoch 91: Avg. Loss = 0.12747416912876852
Epoch 92: Avg. Loss = 0.1274569538213126
Epoch 93: Avg. Loss = 0.12743987153313074
Epoch 94: Avg. Loss = 0.12742292130698524
Epoch 95: Avg. Loss = 0.1274061021913762
Epoch 96: Avg. Loss = 0.1273894132405261
Epoch 97: Avg. Loss = 0.12737285351436314
Epoch 98: Avg. Loss = 0.12735642207850525
Epoch 99: Avg. Loss = 0.12734011800424322
Epoch 100: Avg. Loss = 0.12732394036852376
Epoch 101: Avg. Loss = 0.1273078882539324
Epoch 102: Avg. Loss = 0.12729196074867588
Epoch 103: Avg. Loss = 0.1272761569465645
Epoch 104: Avg. Loss = 0.1272604759469941
Epoch 105: Avg. Loss = 0.12724491685492795
Epoch 106: Avg. Loss = 0.12722947878087823
Epoch 107: Avg. Loss = 0.1272141608408874
Epoch 108: Avg. Loss = 0.12719896215650947
Epoch 109: Avg. Loss = 0.12718388185479057
Epoch 110: Avg. Loss = 0.12716891906825
Epoch 111: Avg. Loss = 0.1271540729348607
Epoch 112: Avg. Loss = 0.12713934259802925
Epoch 113: Avg. Loss = 0.12712472720657647
Epoch 114: Avg. Loss = 0.1271102259147171
Epoch 115: Avg. Loss = 0.12709583788203946
Epoch 116: Avg. Loss = 0.1270815622734854
Epoch 117: Avg. Loss = 0.1270673982593295
Epoch 118: Avg. Loss = 0.12705334501515841
Epoch 119: Avg. Loss = 0.12703940172184985
Epoch 120: Avg. Loss = 0.12702556756555192
Epoch 121: Avg. Loss = 0.1270118417376615
Epoch 122: Avg. Loss = 0.12699822343480338
Epoch 123: Avg. Loss = 0.12698471185880855
Epoch 124: Avg. Loss = 0.12697130621669261
Epoch 125: Avg. Loss = 0.12695800572063431
Epoch 126: Avg. Loss = 0.12694480958795354
Epoch 127: Avg. Loss = 0.1269317170410895
Epoch 128: Avg. Loss = 0.12691872730757864
Epoch 129: Avg. Loss = 0.12690583962003252
Epoch 130: Avg. Loss = 0.12689305321611571
Epoch 131: Avg. Loss = 0.12688036733852315
Epoch 132: Avg. Loss = 0.12686778123495812
Epoch 133: Avg. Loss = 0.12685529415810945
Epoch 134: Avg. Loss = 0.12684290536562898
Epoch 135: Avg. Loss = 0.126830614120109
Epoch 136: Avg. Loss = 0.12681841968905935
Epoch 137: Avg. Loss = 0.1268063213448848
Epoch 138: Avg. Loss = 0.12679431836486194
Epoch 139: Avg. Loss = 0.1267824100311165
Epoch 140: Avg. Loss = 0.1267705956306001
Epoch 141: Avg. Loss = 0.12675887445506728
Epoch 142: Avg. Loss = 0.12674724580105248
Epoch 143: Avg. Loss = 0.12673570896984673
Epoch 144: Avg. Loss = 0.12672426326747455
Epoch 145: Avg. Loss = 0.1267129080046707
Epoch 146: Avg. Loss = 0.12670164249685686
Epoch 147: Avg. Loss = 0.12669046606411835
Epoch 148: Avg. Loss = 0.12667937803118082
Epoch 149: Avg. Loss = 0.12666837772738665
Epoch 150: Avg. Loss = 0.12665746448667192
Epoch 151: Avg. Loss = 0.12664663764754275
Epoch 152: Avg. Loss = 0.12663589655305177
Epoch 153: Avg. Loss = 0.12662524055077495
Epoch 154: Avg. Loss = 0.126614668992788
Epoch 155: Avg. Loss = 0.1266041812356428
Epoch 156: Avg. Loss = 0.126593776640344
Epoch 157: Avg. Loss = 0.12658345457232564
Epoch 158: Avg. Loss = 0.1265732144014274
Epoch 159: Avg. Loss = 0.12656305550187147
Epoch 160: Avg. Loss = 0.1265529772522386
Epoch 161: Avg. Loss = 0.12654297903544515
Epoch 162: Avg. Loss = 0.12653306023871919
Epoch 163: Avg. Loss = 0.12652322025357737
Epoch 164: Avg. Loss = 0.12651345847580114
Epoch 165: Avg. Loss = 0.1265037743054137
Epoch 166: Avg. Loss = 0.1264941671466563
Epoch 167: Avg. Loss = 0.12648463640796498
Epoch 168: Avg. Loss = 0.12647518150194725
Epoch 169: Avg. Loss = 0.12646580184535855
Epoch 170: Avg. Loss = 0.12645649685907923
Epoch 171: Avg. Loss = 0.12644726596809103
Epoch 172: Avg. Loss = 0.12643810860145402
Epoch 173: Avg. Loss = 0.12642902419228313
Epoch 174: Avg. Loss = 0.12642001217772525
Epoch 175: Avg. Loss = 0.12641107199893592
Epoch 176: Avg. Loss = 0.1264022031010563
Epoch 177: Avg. Loss = 0.12639340493319
Epoch 178: Avg. Loss = 0.1263846769483803
Epoch 179: Avg. Loss = 0.12637601860358677
Epoch 180: Avg. Loss = 0.12636742935966272
Epoch 181: Avg. Loss = 0.12635890868133215
Epoch 182: Avg. Loss = 0.12635045603716702
Epoch 183: Avg. Loss = 0.12634207089956426
Epoch 184: Avg. Loss = 0.1263337527447232
Epoch 185: Avg. Loss = 0.1263255010526229
Epoch 186: Avg. Loss = 0.12631731530699952
Epoch 187: Avg. Loss = 0.12630919499532367
Epoch 188: Avg. Loss = 0.12630113960877798
Epoch 189: Avg. Loss = 0.12629314864223468
Epoch 190: Avg. Loss = 0.1262852215942331
Epoch 191: Avg. Loss = 0.12627735796695747
Epoch 192: Avg. Loss = 0.12626955726621458
Epoch 193: Avg. Loss = 0.12626181900141167
Epoch 194: Avg. Loss = 0.12625414268553417
Epoch 195: Avg. Loss = 0.1262465278351238
Epoch 196: Avg. Loss = 0.1262389739702564
Epoch 197: Avg. Loss = 0.12623148061452014
Epoch 198: Avg. Loss = 0.12622404729499362
Epoch 199: Avg. Loss = 0.12621667354222404
Epoch 200: Avg. Loss = 0.1262093588902057
Epoch 201: Avg. Loss = 0.1262021028763579
Epoch 202: Avg. Loss = 0.12619490504150396
Epoch 203: Avg. Loss = 0.12618776492984926
Epoch 204: Avg. Loss = 0.1261806820889601
Epoch 205: Avg. Loss = 0.12617365606974218
Epoch 206: Avg. Loss = 0.12616668642641957
Epoch 207: Avg. Loss = 0.12615977271651319
Epoch 208: Avg. Loss = 0.12615291450082017
Epoch 209: Avg. Loss = 0.1261461113433923
Epoch 210: Avg. Loss = 0.12613936281151555
Epoch 211: Avg. Loss = 0.1261326684756889
Epoch 212: Avg. Loss = 0.12612602790960376
Epoch 213: Avg. Loss = 0.12611944069012312
Epoch 214: Avg. Loss = 0.12611290639726108
Epoch 215: Avg. Loss = 0.12610642461416227
Epoch 216: Avg. Loss = 0.12609999492708124
Epoch 217: Avg. Loss = 0.12609361692536242
Epoch 218: Avg. Loss = 0.12608729020141957
Epoch 219: Avg. Loss = 0.12608101435071578
Epoch 220: Avg. Loss = 0.12607478897174323
Epoch 221: Avg. Loss = 0.1260686136660033
Epoch 222: Avg. Loss = 0.12606248803798653
Epoch 223: Avg. Loss = 0.1260564116951528
Epoch 224: Avg. Loss = 0.12605038424791176
Epoch 225: Avg. Loss = 0.12604440530960287
Epoch 226: Avg. Loss = 0.12603847449647604
Epoch 227: Avg. Loss = 0.1260325914276721
Epoch 228: Avg. Loss = 0.12602675572520342
Epoch 229: Avg. Loss = 0.12602096701393453
Epoch 230: Avg. Loss = 0.126015224921563
Epoch 231: Avg. Loss = 0.1260095290786003
Epoch 232: Avg. Loss = 0.12600387911835273
Epoch 233: Avg. Loss = 0.1259982746769025
Epoch 234: Avg. Loss = 0.12599271539308893
Epoch 235: Avg. Loss = 0.12598720090848958
Epoch 236: Avg. Loss = 0.1259817308674018
Epoch 237: Avg. Loss = 0.12597630491682377
Epoch 238: Avg. Loss = 0.12597092270643653
Epoch 239: Avg. Loss = 0.12596558388858523
Epoch 240: Avg. Loss = 0.12596028811826088
Epoch 241: Avg. Loss = 0.1259550350530823
Epoch 242: Avg. Loss = 0.12594982435327787
Epoch 243: Avg. Loss = 0.1259446556816676
Epoch 244: Avg. Loss = 0.1259395287036451
Epoch 245: Avg. Loss = 0.12593444308715995
Epoch 246: Avg. Loss = 0.12592939850269974
Epoch 247: Avg. Loss = 0.12592439462327248
Epoch 248: Avg. Loss = 0.1259194311243892
Epoch 249: Avg. Loss = 0.12591450768404638
Epoch 250: Avg. Loss = 0.12590962398270855
Epoch 251: Avg. Loss = 0.1259047797032911
Epoch 252: Avg. Loss = 0.125899974531143
Epoch 253: Avg. Loss = 0.1258952081540298
Epoch 254: Avg. Loss = 0.12589048026211672
Epoch 255: Avg. Loss = 0.12588579054795163
Epoch 256: Avg. Loss = 0.1258811387064482
Epoch 257: Avg. Loss = 0.12587652443486935
Epoch 258: Avg. Loss = 0.12587194743281055
Epoch 259: Avg. Loss = 0.1258674074021832
Epoch 260: Avg. Loss = 0.12586290404719835
Epoch 261: Avg. Loss = 0.12585843707435043
Epoch 262: Avg. Loss = 0.12585400619240067
Epoch 263: Avg. Loss = 0.1258496111123613
Epoch 264: Avg. Loss = 0.12584525154747928
Epoch 265: Avg. Loss = 0.12584092721322043
Epoch 266: Avg. Loss = 0.1258366378272536
Epoch 267: Avg. Loss = 0.12583238310943465
Epoch 268: Avg. Loss = 0.12582816278179101
Epoch 269: Avg. Loss = 0.12582397656850597
Epoch 270: Avg. Loss = 0.12581982419590326
Epoch 271: Avg. Loss = 0.12581570539243145
Epoch 272: Avg. Loss = 0.1258116198886488
Epoch 273: Avg. Loss = 0.12580756741720792
Epoch 274: Avg. Loss = 0.1258035477128407
Epoch 275: Avg. Loss = 0.12579956051234323
Epoch 276: Avg. Loss = 0.12579560555456076
Epoch 277: Avg. Loss = 0.12579168258037302
Epoch 278: Avg. Loss = 0.12578779133267917
Epoch 279: Avg. Loss = 0.1257839315563833
Epoch 280: Avg. Loss = 0.12578010299837983
Epoch 281: Avg. Loss = 0.1257763054075388
Epoch 282: Avg. Loss = 0.12577253853469184
Epoch 283: Avg. Loss = 0.12576880213261726
Epoch 284: Avg. Loss = 0.12576509595602633
Epoch 285: Avg. Loss = 0.1257614197615488
Epoch 286: Avg. Loss = 0.12575777330771903
Epoch 287: Avg. Loss = 0.1257541563549618
Epoch 288: Avg. Loss = 0.12575056866557854
Epoch 289: Avg. Loss = 0.12574701000373356
Epoch 290: Avg. Loss = 0.12574348013544023
Epoch 291: Avg. Loss = 0.12573997882854746
Epoch 292: Avg. Loss = 0.12573650585272583
Epoch 293: Avg. Loss = 0.1257330609794546
Epoch 294: Avg. Loss = 0.125729643982008
Epoch 295: Avg. Loss = 0.1257262546354421
Epoch 296: Avg. Loss = 0.12572289271658138
Epoch 297: Avg. Loss = 0.12571955800400586
Epoch 298: Avg. Loss = 0.12571625027803796
Epoch 299: Avg. Loss = 0.1257129693207295
Epoch 300: Avg. Loss = 0.1257097149158489
Epoch 301: Avg. Loss = 0.1257064868488683
Epoch 302: Avg. Loss = 0.12570328490695104
Epoch 303: Avg. Loss = 0.1257001088789388
Epoch 304: Avg. Loss = 0.12569695855533908
Epoch 305: Avg. Loss = 0.12569383372831308
Epoch 306: Avg. Loss = 0.12569073419166288
Epoch 307: Avg. Loss = 0.12568765974081947
Epoch 308: Avg. Loss = 0.12568461017283022
Epoch 309: Avg. Loss = 0.12568158528634718
Epoch 310: Avg. Loss = 0.12567858488161454
Epoch 311: Avg. Loss = 0.12567560876045705
Epoch 312: Avg. Loss = 0.12567265672626796
Epoch 313: Avg. Loss = 0.12566972858399716
Epoch 314: Avg. Loss = 0.12566682414013952
Epoch 315: Avg. Loss = 0.12566394320272326
Epoch 316: Avg. Loss = 0.12566108558129824
Epoch 317: Avg. Loss = 0.12565825108692472
Epoch 318: Avg. Loss = 0.1256554395321616
Epoch 319: Avg. Loss = 0.1256526507310553
Epoch 320: Avg. Loss = 0.12564988449912848
Epoch 321: Avg. Loss = 0.12564714065336874
Epoch 322: Avg. Loss = 0.12564441901221757
Epoch 323: Avg. Loss = 0.12564171939555938
Epoch 324: Avg. Loss = 0.1256390416247104
Epoch 325: Avg. Loss = 0.12563638552240775
Epoch 326: Avg. Loss = 0.125633750912799
Epoch 327: Avg. Loss = 0.12563113762143086
Epoch 328: Avg. Loss = 0.125628545475239
Epoch 329: Avg. Loss = 0.1256259743025372
Epoch 330: Avg. Loss = 0.12562342393300685
Epoch 331: Avg. Loss = 0.12562089419768666
Epoch 332: Avg. Loss = 0.12561838492896205
Epoch 333: Avg. Loss = 0.125615895960555
Epoch 334: Avg. Loss = 0.1256134271275139
Epoch 335: Avg. Loss = 0.12561097826620304
Epoch 336: Avg. Loss = 0.12560854921429296
Epoch 337: Avg. Loss = 0.12560613981075014
Epoch 338: Avg. Loss = 0.12560374989582718
Epoch 339: Avg. Loss = 0.12560137931105284
Epoch 340: Avg. Loss = 0.1255990278992222
Epoch 341: Avg. Loss = 0.12559669550438712
Epoch 342: Avg. Loss = 0.1255943819718464
Epoch 343: Avg. Loss = 0.1255920871481361
Epoch 344: Avg. Loss = 0.12558981088102023
Epoch 345: Avg. Loss = 0.12558755301948116
Epoch 346: Avg. Loss = 0.1255853134137101
Epoch 347: Avg. Loss = 0.12558309191509803
Epoch 348: Avg. Loss = 0.12558088837622622
Epoch 349: Avg. Loss = 0.12557870265085713
Epoch 350: Avg. Loss = 0.12557653459392518
Epoch 351: Avg. Loss = 0.12557438406152777
Epoch 352: Avg. Loss = 0.1255722509109162
Epoch 353: Avg. Loss = 0.12557013500048692
Epoch 354: Avg. Loss = 0.12556803618977228
Epoch 355: Avg. Loss = 0.12556595433943207
Epoch 356: Avg. Loss = 0.1255638893112446
Epoch 357: Avg. Loss = 0.12556184096809808
Epoch 358: Avg. Loss = 0.12555980917398188
Epoch 359: Avg. Loss = 0.12555779379397813
Epoch 360: Avg. Loss = 0.12555579469425304
Epoch 361: Avg. Loss = 0.12555381174204866
Epoch 362: Avg. Loss = 0.1255518448056743
Epoch 363: Avg. Loss = 0.1255498937544984
Epoch 364: Avg. Loss = 0.1255479584589401
Epoch 365: Avg. Loss = 0.12554603879046117
Epoch 366: Avg. Loss = 0.12554413462155783
Epoch 367: Avg. Loss = 0.12554224582575263
Epoch 368: Avg. Loss = 0.1255403722775864
Epoch 369: Avg. Loss = 0.12553851385261058
Epoch 370: Avg. Loss = 0.1255366704273789
Epoch 371: Avg. Loss = 0.12553484187943975
Epoch 372: Avg. Loss = 0.12553302808732844
Epoch 373: Avg. Loss = 0.12553122893055935
Epoch 374: Avg. Loss = 0.12552944428961832
Epoch 375: Avg. Loss = 0.12552767404595505
Epoch 376: Avg. Loss = 0.12552591808197544
Epoch 377: Avg. Loss = 0.1255241762810343
Epoch 378: Avg. Loss = 0.12552244852742755
Epoch 379: Avg. Loss = 0.12552073470638525
Epoch 380: Avg. Loss = 0.1255190347040639
Epoch 381: Avg. Loss = 0.12551734840753925
Epoch 382: Avg. Loss = 0.12551567570479932
Epoch 383: Avg. Loss = 0.12551401648473692
Epoch 384: Avg. Loss = 0.12551237063714252
Epoch 385: Avg. Loss = 0.12551073805269736
Epoch 386: Avg. Loss = 0.1255091186229665
Epoch 387: Avg. Loss = 0.12550751224039142
Epoch 388: Avg. Loss = 0.12550591879828366
Epoch 389: Avg. Loss = 0.12550433819081752
Epoch 390: Avg. Loss = 0.12550277031302357
Epoch 391: Avg. Loss = 0.12550121506078155
Epoch 392: Avg. Loss = 0.12549967233081405
Epoch 393: Avg. Loss = 0.12549814202067947
Epoch 394: Avg. Loss = 0.1254966240287657
Epoch 395: Avg. Loss = 0.1254951182542835
Epoch 396: Avg. Loss = 0.12549362459725977
Epoch 397: Avg. Loss = 0.1254921429585314
Epoch 398: Avg. Loss = 0.12549067323973867
Epoch 399: Avg. Loss = 0.12548921534331894
Epoch 400: Avg. Loss = 0.1254877691725003
Epoch 401: Avg. Loss = 0.12548633463129533
Epoch 402: Avg. Loss = 0.12548491162449493
Epoch 403: Avg. Loss = 0.12548350005766198
Epoch 404: Avg. Loss = 0.1254820998371255
Epoch 405: Avg. Loss = 0.1254807108699741
Epoch 406: Avg. Loss = 0.12547933306405057
Epoch 407: Avg. Loss = 0.1254779663279453
Epoch 408: Avg. Loss = 0.12547661057099072
Epoch 409: Avg. Loss = 0.12547526570325518
Epoch 410: Avg. Loss = 0.12547393163553727
Epoch 411: Avg. Loss = 0.12547260827935994
Epoch 412: Avg. Loss = 0.12547129554696462
Epoch 413: Avg. Loss = 0.12546999335130565
Epoch 414: Avg. Loss = 0.12546870160604456
Epoch 415: Avg. Loss = 0.12546742022554452
Epoch 416: Avg. Loss = 0.12546614912486445
Epoch 417: Avg. Loss = 0.12546488821975385
Epoch 418: Avg. Loss = 0.125463637426647
Epoch 419: Avg. Loss = 0.12546239666265774
Epoch 420: Avg. Loss = 0.12546116584557387
Epoch 421: Avg. Loss = 0.12545994489385176
Epoch 422: Avg. Loss = 0.12545873372661115
Epoch 423: Avg. Loss = 0.12545753226362977
Epoch 424: Avg. Loss = 0.12545634042533813
Epoch 425: Avg. Loss = 0.12545515813281413
Epoch 426: Avg. Loss = 0.12545398530777813
Epoch 427: Avg. Loss = 0.12545282187258766
Epoch 428: Avg. Loss = 0.12545166775023228
Epoch 429: Avg. Loss = 0.1254505228643288
Epoch 430: Avg. Loss = 0.1254493871391159
Epoch 431: Avg. Loss = 0.1254482604994493
Epoch 432: Avg. Loss = 0.12544714287079692
Epoch 433: Avg. Loss = 0.12544603417923383
Epoch 434: Avg. Loss = 0.12544493435143744
Epoch 435: Avg. Loss = 0.1254438433146827
Epoch 436: Avg. Loss = 0.12544276099683724
Epoch 437: Avg. Loss = 0.12544168732635666
Epoch 438: Avg. Loss = 0.1254406222322798
Epoch 439: Avg. Loss = 0.12543956564422412
Epoch 440: Avg. Loss = 0.1254385174923809
Epoch 441: Avg. Loss = 0.1254374777075109
Epoch 442: Avg. Loss = 0.1254364462209394
Epoch 443: Avg. Loss = 0.12543542296455207
Epoch 444: Avg. Loss = 0.12543440787079016
Epoch 445: Avg. Loss = 0.12543340087264626
Epoch 446: Avg. Loss = 0.12543240190365962
Epoch 447: Avg. Loss = 0.12543141089791215
Epoch 448: Avg. Loss = 0.12543042779002345
Epoch 449: Avg. Loss = 0.12542945251514712
Epoch 450: Avg. Loss = 0.12542848500896606
Epoch 451: Avg. Loss = 0.12542752520768835
Epoch 452: Avg. Loss = 0.125426573048043
Epoch 453: Avg. Loss = 0.12542562846727576
Epoch 454: Avg. Loss = 0.1254246914031449
Epoch 455: Avg. Loss = 0.12542376179391726
Epoch 456: Avg. Loss = 0.1254228395783638
Epoch 457: Avg. Loss = 0.125421924695756
Epoch 458: Avg. Loss = 0.1254210170858614
Epoch 459: Avg. Loss = 0.1254201166889399
Epoch 460: Avg. Loss = 0.12541922344573964
Epoch 461: Avg. Loss = 0.12541833729749305
Epoch 462: Avg. Loss = 0.12541745818591296
Epoch 463: Avg. Loss = 0.1254165860531889
Epoch 464: Avg. Loss = 0.12541572084198288
Epoch 465: Avg. Loss = 0.12541486249542597
Epoch 466: Avg. Loss = 0.12541401095711424
Epoch 467: Avg. Loss = 0.1254131661711051
Epoch 468: Avg. Loss = 0.1254123280819136
Epoch 469: Avg. Loss = 0.12541149663450862
Epoch 470: Avg. Loss = 0.12541067177430948

#### Using Xaviers initialization

In [26]:
nin = 2
nhidden = 2
nout = 1

def xavier(nin, nout):
    limit = np.sqrt(6/(nin + nout))
    return np.random.uniform(-limit, limit, (nin, nout))

w1 = xavier(nin, nhidden)
w2 = xavier(nhidden, nout)
print("W1:")
print(w1)

print("\nW2:")
print(w2)

W1:
[[ 0.82526474 -0.87978112]
 [ 1.13086352  0.24788133]]

W2:
[[-0.14486826]
 [-0.94115817]]

#### On Dataset

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

In [12]:
import kagglehub

path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset

In [13]:
df = pd.read_csv(f"{path}/Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [15]:
y_titanic = df['Survived']
X_titanic = df.drop(columns=["Survived", "Name", "Ticket", "Cabin"])

In [16]:
X_titanic["Sex"] = X_titanic["Sex"].map({"male": 0, "female": 1})

In [17]:
X_titanic = pd.get_dummies(X_titanic, columns=["Embarked"], drop_first=True)

In [18]:
X_titanic = X_titanic.fillna(X_titanic.mean())

In [19]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_titanic)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_titanic, test_size=0.2, random_state=42
)

In [21]:
mlp = MLPClassifier(
    hidden_layer_sizes=(10,),
    activation="logistic",
    solver="sgd",
    learning_rate_init=0.01,
    random_state=42,
    max_iter=2000
)

In [22]:
mlp.fit(X_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(10,),
              learning_rate_init=0.01, max_iter=2000, random_state=42,
              solver='sgd')

In [23]:
print("\nWeights (Coefficients):")
for i, coef in enumerate(mlp.coefs_):
    print(f"\nLayer {i} weights:\n", coef)

print("\nBiases (Intercepts):")
for i, intercept in enumerate(mlp.intercepts_):
    print(f"\nLayer {i} biases:\n", intercept)

Weights (Coefficients):

Layer 0 weights:
 [[-1.23055339e-01  2.25620681e-01  1.01667642e-01  7.35710890e-02
  -8.28088878e-02 -2.09522077e-01 -3.20303507e-01  2.44859454e-01
   5.49006183e-03 -3.18626407e-02]
 [ 6.44636711e-02  4.84151132e-01  4.74956217e-01 -2.35314534e-01
  -7.33476544e-01 -2.20375290e-01  1.46765792e-01 -4.04594743e-01
   3.50579576e-01  2.61799303e-01]
 [-6.11237225e-01 -5.28119882e-01 -5.49378933e-01 -2.59416080e-03
   7.90845866e-01  1.97478004e-01 -7.49328947e-01  7.37008587e-01
  -5.90646562e-01 -1.16143157e+00]
 [ 2.71919074e-01 -1.23088466e-01 -2.19473697e-01  2.67269713e-01
  -9.58774522e-02  1.75209728e-01  7.82637785e-02 -4.99441642e-01
   3.08723186e-01  3.47972954e-01]
 [-3.91321060e-02  1.32197702e-01 -1.30177846e-01  2.42529430e-01
  -4.24563288e-01  6.14823518e-02  5.28744039e-02 -3.21939212e-01
   3.18669998e-01 -7.96298749e-04]
 [ 3.08043846e-01  2.32956341e-01  3.16221622e-01  2.56426864e-01
  -3.93360723e-02  2.45309298e-01 -3.05650132e-01 -2.76436875e-01
  -3.05027681e-01 -1.83908629e-01]
 [-2.14706976e-01 -1.71645988e-01  9.48724990e-02 -6.58238249e-02
   6.95309325e-02  1.09519752e-02 -3.00057334e-01  2.59897028e-01
  -4.26945462e-01  1.11503203e-01]
 [ 2.36278736e-01 -1.41149258e-01 -2.62809224e-01  2.00003795e-01
   2.15302289e-02  1.38481388e-01  1.85593297e-01 -2.43354816e-01
  -1.31567545e-02 -7.28897497e-02]
 [ 2.82804168e-01  8.21682262e-02 -7.02693376e-02 -2.94089537e-01
  -2.30153607e-01 -1.02003487e-01  1.77207920e-01 -3.23748451e-02
   2.89831929e-01 -3.01327928e-03]]

Layer 1 weights:
 [[-0.70427366]
 [-0.5863168 ]
 [-0.48674035]
 [ 0.05474363]
 [ 1.46176368]
 [ 0.19552846]
 [-0.7503761 ]
 [ 1.33415929]
 [-0.89791142]
 [-1.17639055]]

Biases (Intercepts):

Layer 0 biases:
 [-0.25255352  0.15515777  0.1993401   0.0478222   0.03301366  0.00455411
 -0.00167376 -0.04598046 -0.27603102 -0.17869244]

Layer 1 biases:
 [0.12189205]